import type { PaxRuntimeMode } from '../../services/pax';
import { formatCurrency } from '../../utils/format';

type DemoReceiptInput = {
  amount: string;
  referenceId: string;
  runtimeMode: PaxRuntimeMode;
};

export function buildDemoReceiptHtml({
  amount,
  referenceId,
  runtimeMode,
}: DemoReceiptInput) {
  const total = formatCurrency(amount);
  const subtotalValue = Number.parseFloat(amount || '0');
  const subTotal = formatCurrency((subtotalValue / 1.0825).toFixed(2));
  const tax = formatCurrency(
    (subtotalValue - subtotalValue / 1.0825).toFixed(2),
  );
  const timestamp = new Date().toLocaleString();

  return `
    <html>
      <head>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            padding: 16px;
            color: #0f172a;
          }
          .header {
            text-align: center;
            margin-bottom: 16px;
          }
          .title {
            font-size: 24px;
            font-weight: 800;
            letter-spacing: 1px;
          }
          .meta,
          .totals {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
          }
          .meta td,
          .totals td {
            padding: 4px 0;
            font-size: 14px;
          }
          .divider {
            border-top: 1px dashed #94a3b8;
            margin: 12px 0;
          }
          .label {
            color: #475569;
          }
          .value {
            text-align: right;
            font-weight: 600;
          }
          .grand-total td {
            font-size: 18px;
            font-weight: 800;
          }
          .footer {
            margin-top: 18px;
            text-align: center;
            font-size: 12px;
            color: #475569;
          }
          .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 999px;
            background: #dbeafe;
            color: #1d4ed8;
            font-weight: 700;
            font-size: 12px;
            margin-top: 6px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">PAX DEMO MARKET</div>
          <div>145 Reference Lane, Demo City</div>
          <div>(555) 010-4242</div>
          <div class="badge">${runtimeMode.toUpperCase()} MODE</div>
        </div>

        <table class="meta">
          <tr><td class="label">Date</td><td class="value">${timestamp}</td></tr>
          <tr><td class="label">Invoice</td><td class="value">${referenceId}</td></tr>
          <tr><td class="label">Terminal</td><td class="value">PAX-A920-PRO</td></tr>
          <tr><td class="label">Cashier</td><td class="value">Demo Operator</td></tr>
        </table>

        <div class="divider"></div>

        <table class="meta">
          <tr><td class="label">1 x Demo Beverage</td><td class="value">${subTotal}</td></tr>
          <tr><td class="label">1 x Signature Snack</td><td class="value">${tax}</td></tr>
        </table>

        <div class="divider"></div>

        <table class="totals">
          <tr><td class="label">Subtotal</td><td class="value">${subTotal}</td></tr>
          <tr><td class="label">Tax</td><td class="value">${tax}</td></tr>
          <tr class="grand-total"><td>Total</td><td class="value">${total}</td></tr>
        </table>

        <div class="divider"></div>

        <table class="meta">
          <tr><td class="label">Payment</td><td class="value">CREDIT</td></tr>
          <tr><td class="label">Status</td><td class="value">APPROVED</td></tr>
        </table>

        <div class="footer">
          <div>Thanks for reviewing the PAX SDK demo.</div>
          <div>This receipt is generated by the built-in HTML template.</div>
        </div>
      </body>
    </html>
  `;
}
